# $FreeBSD$

PACKAGE=lib${LIB}
LIB=	pmcstat
PRIVATELIB=	true

SRCS=	libpmcstat_string.c libpmcstat_logging.c libpmcstat_process.c \
	libpmcstat_image.c libpmcstat_event.c libpmcstat_symbol.c
INCS=	libpmcstat.h

.include <bsd.lib.mk>
